const embed = new Discord.RichEmbed()
      .setDescription ("Performed")
      .setColor (0xdd0b00)
      .setAuthor (`${message.author.username}#${message.author.discriminator}`, message.author.avatarURL)
      .addField (' User', `${user} whose ID is ${user.id}`)
      .addField ('Reason ', reason)
      .addField (' By', `${message.author} whose ID is ${message.author.id}`)
      .addField (' In', message.channel)
      .addField ('At', message.createdAt)
      chan.send(embed)